version: "3.4"
services:
 Portfolio:
   image: node:alpine
   container_name: Portfolio
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true